# Image to Binary Conversion

In [71]:
# Importing all the required libraries
import pandas as pd
import numpy as np
from PIL import Image
import csv
import os

In [21]:
pd.options.display.max_columns = 23
pd.options.display.max_rows = 80

In [51]:
img = Image.open(r"C:\Users\deepa\Panda 2024\CAPTCHA Break\Jupyter\dataset\Char_1\0\cap_1066.jpg")
img1 = Image.open(r"C:\Users\deepa\Panda 2024\CAPTCHA Break\Jupyter\dataset\Char_1\3\cap_1026.jpg")
img

In [52]:
img1

In [53]:
img_arr = np.array(img)
img1_arr = np.array(img1)
img_arr

array([[249, 249, 249, ..., 249, 249, 249],
       [249, 249, 249, ..., 249, 249, 249],
       [249, 249, 249, ..., 249, 249, 249],
       ...,
       [249, 249, 249, ..., 249, 249, 249],
       [249, 249, 249, ..., 249, 249, 249],
       [249, 249, 249, ..., 249, 249, 249]], dtype=uint8)

In [54]:
img1_arr

array([[249, 249, 249, ..., 249, 249, 249],
       [249, 249, 249, ..., 249, 249, 249],
       [249, 249, 249, ..., 249, 249, 249],
       ...,
       [249, 249, 249, ..., 249, 249, 249],
       [249, 249, 249, ..., 249, 249, 249],
       [249, 249, 249, ..., 249, 249, 249]], dtype=uint8)

In [55]:
img_arr.shape

(80, 23)

In [56]:
img_arr[0][0]

249

In [57]:
height, width = img_arr.shape
height

80

In [58]:
for i in range(height):
    for j in range(width):
        if img_arr[i][j] >= 128:
            img_arr[i][j] = 0
        else:
            img_arr[i][j] = 1
            
img_arr

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [59]:
for i in range(height):
    for j in range(width):
        if img1_arr[i][j] >= 128:
            img1_arr[i][j] = 0
        else:
            img1_arr[i][j] = 1
            
img1_arr

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [60]:
df = pd.DataFrame(img_arr)
df

0   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15  16  17  \
0    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
1    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
2    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
3    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
4    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
5    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
6    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
7    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
8    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
9    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
10   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
11   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
12   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
13   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
14   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
15   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
16   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
17   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
18   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
19   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
20   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
21   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
22   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
23   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
24   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
25   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
26   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
27   0   0   0   0   0   0   0   0   0   0   0   0   0   0   1   1   1   1   
28   0   0   0   0   0   0   0   0   0   0   0   0   1   1   1   0   0   0   
29   0   0   0   0   0   0   0   0   0   0   0   1   1   1   0   0   0   0   
30   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
31   0   0   0   0   0   0   0   0   0   1   1   1   0   0   0   0   0   0   
32   0   0   0   0   0   0   0   0   1   1   1   1   0   0   0   0   0   0   
33   0   0   0   0   0   0   0   0   1   1   1   0   0   0   0   0   0   0   
34   0   0   0   0   0   0   0   1   1   1   1   0   0   0   0   0   0   0   
35   0   0   0   0   0   0   0   1   1   1   0   0   0   0   0   0   0   0   
36   0   0   0   0   0   0   1   1   1   1   0   0   0   0   0   0   0   0   
37   0   0   0   0   0   0   1   1   1   1   0   0   0   0   0   0   0   0   
38   0   0   0   0   0   1   1   1   1   0   0   0   0   0   0   0   0   0   
39   0   0   0   0   0   1   1   1   1   0   0   0   0   0   0   0   0   0   
40   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
41   0   0   0   0   1   1   1   1   1   0   0   0   0   0   0   0   0   0   
42   0   0   0   0   1   1   1   1   0   0   0   0   0   0   0   0   0   0   
43   0   0   0   0   1   1   1   1   0   0   0   0   0   0   0   0   0   0   
44   0   0   0   1   1   1   1   1   0   0   0   0   0   0   0   0   0   0   
45   0   0   0   1   1   1   1   1   0   0   0   0   0   0   0   0   0   0   
46   0   0   0   1   1   1   1   1   0   0   0   0   0   0   0   0   0   0   
47   0   0   0   1   1   1   1   0   0   0   0   0   0   0   0   0   0   0   
48   0   0   0   1   1   1   1   0   0   0   0   0   0   0   0   0   0   0   
49   0   0   0   1   1   1   1   0   0   0   0   0   0   0   0   0   0   1   
50   0   0   0   0   0   0

In [61]:
reshape_arr = img_arr.reshape(1,1840)
reshape1_arr = img1_arr.reshape(1,1840)

In [62]:
reshape_arr = pd.DataFrame(reshape_arr)
reshape_arr

0     1     2     3     4     5     6     7     8     9     10    ...  \
0     0     0     0     0     0     0     0     0     0     0     0  ...   

   1829  1830  1831  1832  1833  1834  1835  1836  1837  1838  1839  
0     0     0     0     0     0     0     0     0     0     0     0  

[1 rows x 1840 columns]

In [90]:
reshape1_arr = pd.DataFrame(reshape1_arr)
reshape1_arr

0     1     2     3     4     5     6     7     8     9     10    ...  \
0     0     0     0     0     0     0     0     0     0     0     0  ...   

   1829  1830  1831  1832  1833  1834  1835  1836  1837  1838  1839  
0     0     0     0     0     0     0     0     0     0     0     0  

[1 rows x 1840 columns]

In [41]:
reshape_arr.to_csv(r"C:\Users\deepa\Downloads\test.csv")

In [70]:
reshape1_arr.to_csv(r"C:\Users\deepa\Downloads\test.csv",mode="a",header=False)

In [66]:
with open(r"C:\Users\deepa\Downloads\test.csv","a") as file:
    file.write("DeepaK Pawar")

In [36]:
img_arr

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [72]:
os.listdir()

['.ipynb_checkpoints',
 'CAPTCHA Break - Captcha Cropping.ipynb',
 'CAPTCHA Break - Web Scrapping.ipynb',
 'Captcha break project.ipynb',
 'cropped',
 'dataset',
 'downloaded_images',
 'new_file.csv',
 'temp']

In [73]:
os.getcwd()

'C:\\Users\\deepa\\Panda 2024\\CAPTCHA Break\\Jupyter'

In [95]:
os.listdir(os.path.join(os.getcwd(),"dataset","char_1"))

['0',
 '1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 'A',
 'B',
 'C',
 'D',
 'E',
 'F',
 'G',
 'H',
 'I',
 'J',
 'K',
 'L',
 'M',
 'N',
 'O',
 'P',
 'Q',
 'R',
 'S',
 'T',
 'U',
 'V',
 'W',
 'X',
 'Y',
 'Z']

# Conversion in binary and save in csv for character 1

In [114]:
m = "w"
ind = True
h = True
for folder in os.listdir(os.path.join(os.getcwd(),"dataset","char_1")):
    for file in os.listdir(os.path.join(os.getcwd(),"dataset","char_1",folder)):
        path = os.path.join(os.getcwd(),"dataset","char_1",folder,file)
        img = Image.open(path)
        img_arr = np.array(img)
        height, width = img_arr.shape
        for i in range(height):
            for j in range(width):
                if img_arr[i][j] >= 128:
                    img_arr[i][j] = 0
                else:
                    img_arr[i][j] = 1
        reshape_img_arr = img_arr.reshape(1,height*width)
        reshape_img_arr = pd.DataFrame(reshape_img_arr)
        if folder in ["0","1","2","3","4","5","6","7","8","9"]:
            reshape_img_arr[height*width] = ord(folder)-48
            reshape_img_arr.to_csv(r"C:\Users\deepa\Downloads\char1.csv", mode=m, index=ind, header= h)
        if folder in ["A","B","C","D","E","F","G","H","I","J","K","L","M","N","O","P","Q","R","S","T","U","V","W","X","Y","Z"]:
            reshape_img_arr[height*width] = ord(folder)-55
            reshape_img_arr.to_csv(r"C:\Users\deepa\Downloads\char1.csv", mode=m, index=ind, header= h)
        m = "a"
        ind = True
        h = False

In [126]:
# Conversion in binary and save in csv for all character
var = 1
for directory in os.listdir(os.path.join(os.getcwd(),"dataset")):
    m = "w"
    ind = True
    h = True
    for folder in os.listdir(os.path.join(os.getcwd(),"dataset",directory)):
        for file in os.listdir(os.path.join(os.getcwd(),"dataset",directory,folder)):
            path = os.path.join(os.getcwd(),"dataset",directory,folder,file)
            img = Image.open(path)
            img_arr = np.array(img)
            height, width = img_arr.shape
            for i in range(height):
                for j in range(width):
                    if img_arr[i][j] >= 128:
                        img_arr[i][j] = 0
                    else:
                        img_arr[i][j] = 1
            reshape_img_arr = img_arr.reshape(1,height*width)
            reshape_img_arr = pd.DataFrame(reshape_img_arr)
            if folder in ["0","1","2","3","4","5","6","7","8","9"]:
                reshape_img_arr[height*width] = ord(folder)-48
                reshape_img_arr.to_csv(rf"C:\Users\deepa\Downloads\char{var}.csv", mode=m, index=ind, header= h)
            if folder in ["A","B","C","D","E","F","G","H","I","J","K","L","M","N","O","P","Q","R","S","T","U","V","W","X","Y","Z"]:
                reshape_img_arr[height*width] = ord(folder)-55
                reshape_img_arr.to_csv(rf"C:\Users\deepa\Downloads\char{var}.csv", mode=m, index=ind, header= h)
            m = "a"
            ind = True
            h = False
    print(var)
    var = var + 1

0
0    0
Name: 1840, dtype: int64
1
0    1
Name: 1840, dtype: int64
2
0    2
Name: 1840, dtype: int64
3
0    3
Name: 1840, dtype: int64
4
0    4
Name: 1840, dtype: int64
5
0    5
Name: 1840, dtype: int64
6
0    6
Name: 1840, dtype: int64
7
0    7
Name: 1840, dtype: int64
8
0    8
Name: 1840, dtype: int64
9
0    9
Name: 1840, dtype: int64
A
0    10
Name: 1840, dtype: int64
B
0    11
Name: 1840, dtype: int64
C
0    12
Name: 1840, dtype: int64
D
0    13
Name: 1840, dtype: int64
E
0    14
Name: 1840, dtype: int64
F
0    15
Name: 1840, dtype: int64
G
0    16
Name: 1840, dtype: int64
H
0    17
Name: 1840, dtype: int64
I
0    18
Name: 1840, dtype: int64
J
0    19
Name: 1840, dtype: int64
K
0    20
Name: 1840, dtype: int64
L
0    21
Name: 1840, dtype: int64
M
0    22
Name: 1840, dtype: int64
N
0    23
Name: 1840, dtype: int64
O
0    24
Name: 1840, dtype: int64
P
0    25
Name: 1840, dtype: int64
Q
0    26
Name: 1840, dtype: int64
R
0    27
Name: 1840, dtype: int64
S
0    28
Name: 1840, dtype: i

In [109]:
type(ord('0'))

int

In [117]:
os.listdir(os.path.join(os.getcwd(),"dataset"))

['Char_1', 'Char_2', 'Char_3', 'Char_4', 'Char_5', 'Char_6']

# Model Training

In [128]:
import pandas as pd
import numpy as np

from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error

In [149]:
df = pd.read_csv(r"C:\Users\deepa\Downloads\char3.csv")
df

Unnamed: 0  0  1  2  3  4  5  6  7  8  9  ...  1830  1831  1832  1833  \
0              0  0  0  0  0  0  0  0  0  0  0  ...     0     0     0     0   
1              0  0  0  0  0  0  0  0  0  0  0  ...     0     0     0     0   
2              0  0  0  0  0  0  0  0  0  0  0  ...     0     0     0     0   
3              0  0  0  0  0  0  0  0  0  0  0  ...     0     0     0     0   
4              0  0  0  0  0  0  0  0  0  0  0  ...     0     0     0     0   
...          ... .. .. .. .. .. .. .. .. .. ..  ...   ...   ...   ...   ...   
4346           0  0  0  0  0  0  0  0  0  0  0  ...     0     0     0     0   
4347           0  0  0  0  0  0  0  0  0  0  0  ...     0     0     0     0   
4348           0  0  0  0  0  0  0  0  0  0  0  ...     0     0     0     0   
4349           0  0  0  0  0  0  0  0  0  0  0  ...     0     0     0     0   
4350           0  0  0  0  0  0  0  0  0  0  0  ...     0     0     0     0   

      1834  1835  1836  1837  1838  1839  1840  
0        0     0     0     0     0     0     0  
1        0     0     0     0     0     0     0  
2        0     0     0     0     0     0     0  
3        0     0     0     0     0     0     0  
4        0     0     0     0     0     0     0  
...    ...   ...   ...   ...   ...   ...   ...  
4346     0     0     0     0     0     0    35  
4347     0     0     0     0     0     0    35  
4348     0     0     0     0     0     0    35  
4349     0     0     0     0     0     0    35  
4350     0     0     0     0     0     0    35  

[4351 rows x 1842 columns]

In [150]:
X = df.drop("1840",axis=1)
X

Unnamed: 0  0  1  2  3  4  5  6  7  8  9  ...  1829  1830  1831  1832  \
0              0  0  0  0  0  0  0  0  0  0  0  ...     0     0     0     0   
1              0  0  0  0  0  0  0  0  0  0  0  ...     0     0     0     0   
2              0  0  0  0  0  0  0  0  0  0  0  ...     0     0     0     0   
3              0  0  0  0  0  0  0  0  0  0  0  ...     0     0     0     0   
4              0  0  0  0  0  0  0  0  0  0  0  ...     0     0     0     0   
...          ... .. .. .. .. .. .. .. .. .. ..  ...   ...   ...   ...   ...   
4346           0  0  0  0  0  0  0  0  0  0  0  ...     0     0     0     0   
4347           0  0  0  0  0  0  0  0  0  0  0  ...     0     0     0     0   
4348           0  0  0  0  0  0  0  0  0  0  0  ...     0     0     0     0   
4349           0  0  0  0  0  0  0  0  0  0  0  ...     0     0     0     0   
4350           0  0  0  0  0  0  0  0  0  0  0  ...     0     0     0     0   

      1833  1834  1835  1836  1837  1838  1839  
0        0     0     0     0     0     0     0  
1        0     0     0     0     0     0     0  
2        0     0     0     0     0     0     0  
3        0     0     0     0     0     0     0  
4        0     0     0     0     0     0     0  
...    ...   ...   ...   ...   ...   ...   ...  
4346     0     0     0     0     0     0     0  
4347     0     0     0     0     0     0     0  
4348     0     0     0     0     0     0     0  
4349     0     0     0     0     0     0     0  
4350     0     0     0     0     0     0     0  

[4351 rows x 1841 columns]

In [151]:
y = df[["1840"]]
y

1840
0        0
1        0
2        0
3        0
4        0
...    ...
4346    35
4347    35
4348    35
4349    35
4350    35

[4351 rows x 1 columns]

In [152]:
type(X)

pandas.core.frame.DataFrame

In [153]:
type(y)

pandas.core.frame.DataFrame

In [154]:
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.2,random_state=42)

In [155]:
X_train

Unnamed: 0  0  1  2  3  4  5  6  7  8  9  ...  1829  1830  1831  1832  \
1200           0  0  0  0  0  0  0  0  0  0  0  ...     0     0     0     0   
1643           0  0  0  0  0  0  0  0  0  0  0  ...     0     0     0     0   
322            0  0  0  0  0  0  0  0  0  0  0  ...     0     0     0     0   
805            0  0  0  0  0  0  0  0  0  0  0  ...     0     0     0     0   
2228           0  0  0  0  0  0  0  0  0  0  0  ...     0     0     0     0   
...          ... .. .. .. .. .. .. .. .. .. ..  ...   ...   ...   ...   ...   
3444           0  0  0  0  0  0  0  0  0  0  0  ...     0     0     0     0   
466            0  0  0  0  0  0  0  0  0  0  0  ...     0     0     0     0   
3092           0  0  0  0  0  0  0  0  0  0  0  ...     0     0     0     0   
3772           0  0  0  0  0  0  0  0  0  0  0  ...     0     0     0     0   
860            0  0  0  0  0  0  0  0  0  0  0  ...     0     0     0     0   

      1833  1834  1835  1836  1837  1838  1839  
1200     0     0     0     0     0     0     0  
1643     0     0     0     0     0     0     0  
322      0     0     0     0     0     0     0  
805      0     0     0     0     0     0     0  
2228     0     0     0     0     0     0     0  
...    ...   ...   ...   ...   ...   ...   ...  
3444     0     0     0     0     0     0     0  
466      0     0     0     0     0     0     0  
3092     0     0     0     0     0     0     0  
3772     0     0     0     0     0     0     0  
860      0     0     0     0     0     0     0  

[3480 rows x 1841 columns]

In [156]:
y_train

1840
1200    10
1643    13
322      2
805      6
2228    18
...    ...
3444    28
466      3
3092    25
3772    31
860      7

[3480 rows x 1 columns]

In [157]:
rf = RandomForestRegressor()
rf.fit(X_train,y_train)

C:\Users\deepa\AppData\Local\Temp\ipykernel_30268\1932820455.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf.fit(X_train,y_train)


RandomForestRegressor()

In [158]:
y_pred = rf.predict(X_test)

In [159]:
y_pred

array([ 4.        , 13.        , 25.        ,  4.        , 12.        ,
        3.        , 30.        , 22.        , 34.        , 35.        ,
       32.        , 29.        ,  1.        , 35.        , 10.        ,
       20.        , 21.        , 10.        ,  2.        , 29.        ,
        0.        ,  6.        ,  2.        , 27.        , 27.        ,
        0.        , 16.        , 23.        , 18.        , 28.        ,
        2.        , 13.        , 17.        , 14.        , 18.        ,
        7.        ,  6.        ,  1.        ,  2.        , 35.        ,
       25.        , 10.        ,  8.        , 20.        , 12.        ,
       17.        , 34.        , 14.        ,  8.        , 27.        ,
        1.        , 35.        , 35.        , 35.        ,  8.        ,
       32.53      , 30.        , 26.        , 21.        , 32.06      ,
        8.        , 11.10300036, 12.        ,  9.        , 22.        ,
        6.        , 32.        ,  9.        , 35.        , 23.  

In [160]:
score = r2_score(y_test,y_pred)
score

0.9991910298058592